[package]
name = "lf-sll"
version = "0.0.3"
description = "A lock-free singly-linked list"
authors = ["Remis <remis.thoughts@gmail.com>"]
license = "Apache-2.0"
repository = "https://github.com/remis-thoughts/lf-sll"
readme = "README.md"

[lib]
name = "lfsll"
